environment:
  global:
    RANDOM_SEED: 0
  matrix:
    - PYTHON_MAJOR: 3
      PYTHON_MINOR: 7

cache:
  - .venv -> poetry.lock


clone_depth: 5

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install: pip install -e .[tests]

test_script: pytest -rsv
