dist: xenial

language: python
python:
  - 3.7
  
services:
  - xvfb

#cache:
#  pip: true
#  directories:
#    - ${VIRTUAL_ENV}

env:
  global:
    - RANDOM_SEED=0

before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - make doctor

install:
  - make install

script:
  - pytest


notifications:
  email:
    on_success: never
    on_failure: never
