dist: xenial

language: python
sudo: required
python:
  - 3.7
  
#services:
#  - xvfb

#cache:
#  pip: true
#  directories:
#    - ${VIRTUAL_ENV}

env:
  global:
    - RANDOM_SEED=0

before_install:
  - sudo apt-get install -y libdbus-1-3 libxkbcommon-x11-0
  - sudo apt-get install -y xvfb herbstluftwm
  - sudo apt-add-repository ppa:beineri/opt-qt551 -y
  - sudo apt-get install qt-latest
  - source /opt/qt55/bin/qt55-env.sh
#  - sudo apt-get install -y python3-pyqt5 python3-pyqt5.{qtsvg,qtwebkit,qtopengl}
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - make doctor

install:
  - sudo mkdir -p /builds && sudo chmod a+rw /builds
  - sudo mkdir -p /downloads && sudo chmod a+rw /downloads
  - curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.17/sip-4.17.tar.gz
  - curl -L -o /downloads/pyqt.tar.gz http://skylink.dl.sourceforge.net/project/pyqt/PyQt5/PyQt-5.5.1/PyQt-gpl-5.5.1.tar.gz
  - tar xzf /downloads/sip.tar.gz -C /builds --keep-newer-files
  - tar xzf /downloads/pyqt.tar.gz -C /builds --keep-newer-files
  - cd /builds/sip-4.17 && python configure.py && sudo make && sudo make install
  - cd /builds/PyQt-gpl-5.5.1 && python configure.py --confirm-license && sudo make && sudo make install
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX +render -noreset"
  - sleep 3
  - make install

before_script:
  - "herbstluftwm &"
  - sleep 1

script:
  - pytest


notifications:
  email:
    on_success: never
    on_failure: never
