site_name: scimap
site_description: Single-Cell Image Analysis Package
site_author: Ajit Johnson Nirmal

repo_url: https://github.com/ajitjohnson/scimap
edit_uri: https://github.com/ajitjohnson/scimap/edit/master/docs

theme: readthedocs

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Home: index.md
  - Usage Principles: usage_principles.md
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
