site_name: scimap
site_description: Single-Cell Image Analysis Package
site_author: Ajit Johnson Nirmal

repo_url: https://github.com/ajitjohnson/scimap
edit_uri: https://github.com/ajitjohnson/scimap/edit/master/docs

theme: readthedocs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css: [extra.css]

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Tools: tools.md
  - Tutorials:
    - Getting Started: tutorials/scimap-tutorial-getting-started.ipynb
    - Cell Phenotyping: tutorials/scimap-tutorial-cell-phenotyping.ipynb
  - About:
    - Release Notes: about/changelog.md
    - Contributing: about/contributing.md
    - License: about/license.md
