site_name: scimap
site_description: Single-Cell Image Analysis Package
site_author: Ajit Johnson Nirmal

repo_url: https://github.com/ajitjohnson/scimap
edit_uri: https://github.com/ajitjohnson/scimap/edit/master/docs

theme:
  name: readthedocs
  titles_only: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

extra_css: [extra.css]

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Available tools: tools.md
  - Pre-processing:
    - pp.mcmicro_to_scimap: pp/sm.pp.mcmicro_to_scimap.md
    - pp.rescale: pp/sm.pp.rescale.md
  - Tools:
    - tl.phenotype_cells: tl/sm.tl.phenotype_cells.md
  - Plotting:
    - pl.gate_finder: pl/sm.pl.gate_finder.md
    - pl.image_viewer: pl/sm.pl.image_viewer.md
  - Tutorials:
    - Load the Data: tutorials/scimap-tutorial-getting-started.md
    - Cell Phenotyping: tutorials/scimap-tutorial-cell-phenotyping.md
  - About:
    - Release Notes: about/changelog.md
    - License: about/license.md
