site_name: scimap
site_description: Single-Cell Image Analysis Package
site_author: Ajit Johnson Nirmal

repo_url: https://github.com/ajitjohnson/scimap
edit_uri: https://github.com/ajitjohnson/scimap/edit/master/docs

# mkdocs.yml
theme:
  name: "material"
  logo: ./assets/favicon.png
  favicon: ./assets/favicon.png
  features:
    - navigation.instant
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      toggle:
        primary: teal
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
    - Home: 'index.md'
    - Getting Started: 'Getting Started.md'
    - Tools Shortcut: 'Tools Shortcut.md'
    - SCIMAP Functions:
        - Pre Processing:
            - mcmicro_to_scimap: 'Functions/pp/mcmicro_to_scimap.md'
            - rescale: 'Functions/pp/rescale.md'
            - combat: 'Functions/pp/combat.md'
        - Tools:
            - phenotype_cells: 'Functions/tl/phenotype_cells.md'
            - cluster: 'Functions/tl/cluster.md'
            - umap: 'Functions/tl/umap.md'
            - foldchange: 'Functions/tl/foldchange.md'
            - spatial_distance: 'Functions/tl/spatial_distance.md'
            - spatial_interaction: 'Functions/tl/spatial_interaction.md'
            - spatial_count: 'Functions/tl/spatial_count.md'
            - spatial_lda: 'Functions/tl/spatial_lda.md'
            - spatial_expression: 'Functions/tl/spatial_expression.md'
            - spatial_cluster: 'Functions/tl/spatial_cluster.md'
            - spatial_pscore: 'Functions/tl/spatial_pscore.md'
            - spatial_aggregate: 'Functions/tl/spatial_aggregate.md'
            - spatial_similarity_search: 'Functions/tl/spatial_similarity_search.md'            
        - Plotting Functions:
            - image_viewer: 'Functions/pl/image_viewer.md'
            - addROI_image: 'Functions/pl/addROI_image.md'
            - gate_finder: 'Functions/pl/gate_finder.md'
            - distPlot: 'Functions/pl/distPlot.md'
            - densityPlot2D: 'Functions/pl/densityPlot2D.md'
            - cluster_plots: 'Functions/pl/cluster_plots.md'
            - umap: 'Functions/pl/umap.md'
            - foldchange: 'Functions/pl/foldchange.md'
            - spatial_scatterPlot: 'Functions/pl/spatial_scatterPlot.md'
            - spatial_distance: 'Functions/pl/spatial_distance.md'
            - spatial_interaction: 'Functions/pl/spatial_interaction.md'
            - spatial_pscore: 'Functions/pl/spatial_pscore.md'
            - stacked_barplot: 'Functions/pl/stacked_barplot.md'
            - pie: 'Functions/pl/pie.md'
            - voronoi: 'Functions/pl/voronoi.md'
        - Helper Functions:
            - classify: 'Functions/hl/classify.md'
            - rename: 'Functions/hl/rename.md'
            - addROI_omero: 'Functions/hl/addROI_omero.md'
            - dropFeatures: 'Functions/hl/dropFeatures.md'
            - merge_adata_obs: 'Functions/hl/merge_adata_obs.md'
            - animate: 'Functions/hl/animate.md'
            - scimap_to_csv: 'Functions/hl/scimap_to_csv.md'
    - Tutorials:
        - Getting Started with Scimap: 'tutorials/1-scimap-tutorial-getting-started.md'
        - Cell-Phenotyping using Scimap: 'tutorials/2-scimap-tutorial-cell-phenotyping.md'
        - Cell-Phenotyping and adding ROIs: 'tutorials/3-Cell_Type_calling_and_adding_ROIs.md'
        - CellType Proportion Exploration: 'tutorials/4-CellType_Proportion_Exploration.md'
        - Simple Spatial Analysis: 'tutorials/5-Simple_Spatial_Analysis.md'
        - Animate with scimap: 'tutorials/6_animate_with_scimap.md'

plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          heading_level: 4
- search:
    prebuild_index: true
- autorefs

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes
  - meta
  - tables
  - markdown.extensions.tables
  - pymdownx.highlight:
      linenums: true

extra_css:
  - stylesheets/extra.css

    
extra:
  analytics:
    provider: google
    property: G-22X9HCL4YP
  copyright: Copyright &copy; 2020 - 2022 Ajit Johnson Nirmal
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ajitjohnson_n
      name: Twitter
