site_name: scimap
site_description: Single-Cell Image Analysis Package
site_author: Ajit Johnson Nirmal

repo_url: https://github.com/ajitjohnson/scimap
edit_uri: https://github.com/ajitjohnson/scimap/edit/master/docs

# mkdocs.yml
theme:
  name: "material"
  logo: assets/favicon.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
  palette:
    - scheme: default
      primary: teal
      toggle:
        primary: teal
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_signature_annotations: no
          heading_level: 4
- search:
    prebuild_index: true
- autorefs

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes
  - meta
  - tables
  - markdown.extensions.tables
  - pymdownx.highlight:
      linenums: true

extra_css:
  - stylesheets/extra.css

extra:
  copyright: Copyright &copy; 2020 - 2021 Ajit Johnson Nirmal
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ajitjohnson_n
      name: Twitter
