name: docs
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8
          architecture: x64
      #- run: pip install scimap mkdocs-material mkdocstrings
      - run: pip install mkdocs-material mkdocstrings
      - run: mkdocs gh-deploy --force
